
- name: Install rtmp
  apt:
    name: [libnginx-mod-rtmp, ffmpeg]
    state: present

- name: Copy nginx.conf
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf

- name: copy limits.conf
  copy:
    src: limits.conf
    dest: /etc/security/limits.conf

- name: copy common-session
  copy:
    src: common-session
    dest: /etc/pam.d/common-session

- name: Copy rtmp.conf
  template:
    src: rtmp.conf.j2
    dest: /etc/nginx/sites-enabled/rtmp.conf

- name: Copy stream.conf
  copy:
    src: stream.conf
    dest: /etc/nginx/sites-enabled/stream.conf

- name: Copy certificat
  copy:
    src: "{{ ssl_certificate }}"
    dest: "/etc/ssl/certs/"

- name: copy key cert
  copy:
    src: "{{ ssl_certificate_key }}"
    dest: "/etc/ssl/private/"

- name: Create directory for tmpfs filesystem
  file:
    state: directory
    path: /tmp/hls

- name: Configure and mount tmpfs filesystem
  mount:
    path: /tmp/hls
    fstype: tmpfs
    src: tmpfs
    state: mounted

- name: Start
  become: yes
  service: name=nginx state=started enabled=true
