- name: install libraries needed
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - xvfb
    - npm
    - gconf-service
    - libgconf-2-4
    - libappindicator1

- name: apt-key add
  shell: 'curl -sS -o - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add'

- name: apt-key add
  shell: echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list

- name: Update apt-get repo and cache
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

- name: install google-chrome-stable
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - google-chrome-stable

