---
elasticsearch_version: '6.x'
elasticsearch_package_state: present

elasticsearch_service_state: started
elasticsearch_service_enabled: true

elasticsearch_network_host: localhost
elasticsearch_http_port: 9200

elasticsearch_cluster_name: pod-application
elasticsearch_node_name: pod-1
elasticsearch_unicast_hosts: ["127.0.0.1"]
