---

galaxy_info:
  author: 'arillso'
  company: 'arillso'
  description: 'Ansible role for installs and configures logratet on RHEL/CentOS or Debian/Ubuntu'
  license: MIT
  min_ansible_version: 2.7
  platforms:
    - name: Debian
      versions:
        - wheezy
        - jessie
        - stretch
    - name: Ubuntu
      versions:
        - trusty
        - xenial
    - name: EL
      versions:
        - 6
        - 7

  galaxy_tags:
    - system
    - logrotate
    - log
    - rotate
